//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_02_2020_RegistrationModule.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RegTable
    {
        public int Id { get; set; }
        //[Display(Name = "Name")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Name is required")]
        public string Name { get; set; }
        //[Display(Name = "EmailId")]
        //[Required(AllowEmptyStrings = false,ErrorMessage ="EmailId is required")]
        //[DataType(DataType.EmailAddress)]
        public string EmailId { get; set; }
        //[Display(Name ="Pasword")]
        //[Required(AllowEmptyStrings =false,ErrorMessage ="Password is required")]
        //[DataType(DataType.Password)]
        public string Password { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }
}
